import { Metadata } from "next";
import { ThemeProvider } from "./components/theme-provider";

export const metadata: Metadata = {
	title: {
		// absolute: "Absolute learning",
		default: "Next.js learning",
		template: "%s | Next.js",
	},
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<ThemeProvider>
				<body>
					<header>
						<p>Header</p>
					</header>
					{children}
					<footer>
						<p>Footer</p>
					</footer>
				</body>
			</ThemeProvider>
		</html>
	);
}
