import { Metadata } from "next";

export const metadata: Metadata = {
	title: {
		// absolute: "Absolute learning",
		default: "Next.js learning",
		template: "%s | Next.js",
	},
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<header>
					<p>Header</p>
				</header>
				{children}
				<footer>
					<p>Footer</p>
				</footer>
			</body>
		</html>
	);
}
